name = "SatelliteToolboxBase"
uuid = "9e17983a-0463-41a7-9a16-1682db6d8b66"
license = "MIT"
desc = "Base constants, functions, and types for the SatelliteToolbox.jl ecosystem"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.2.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Crayons = "4"
ReferenceFrameRotations = "3"
SnoopPrecompile = "1"
StaticArrays = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
